# ────────────────────────────────────────────────────────────────
# 여행지 데이터 (DB 미사용 - 딕셔너리 리스트)
# ────────────────────────────────────────────────────────────────

TRAVEL_DATA = [
    {
        "id": 1,
        "name": "제주도",
        "category": "자연",
        "region": "국내",
        "price": 350000,
        "rating": 4.8,
        "description": "한국 최대의 섬으로 오름, 한라산, 해변 등 다양한 자연경관을 즐길 수 있습니다.",
        "image": "https://images.unsplash.com/photo-1580739865038-aaf3e6577208?w=400",
        "tags": ["자연", "해변", "오름", "한라산"],
    },
    {
        "id": 2,
        "name": "경주",
        "category": "역사",
        "region": "국내",
        "price": 150000,
        "rating": 4.6,
        "description": "신라의 수도였던 경주는 불국사, 석굴암 등 유네스코 세계유산을 보유한 역사 도시입니다.",
        "image": "https://images.unsplash.com/photo-1579462475143-1b5c84d96d0b?w=400",
        "tags": ["역사", "불국사", "유네스코", "고도"],
    },
    {
        "id": 3,
        "name": "도쿄",
        "category": "도시",
        "region": "해외",
        "price": 900000,
        "rating": 4.7,
        "description": "현대와 전통이 공존하는 일본의 수도. 시부야, 아사쿠사, 신주쿠 등 다채로운 명소가 있습니다.",
        "image": "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400",
        "tags": ["도시", "쇼핑", "음식", "일본"],
    },
    {
        "id": 4,
        "name": "발리",
        "category": "휴양",
        "region": "해외",
        "price": 1200000,
        "rating": 4.9,
        "description": "인도네시아의 열대 섬. 아름다운 해변, 사원, 논밭이 어우러진 힐링 여행지입니다.",
        "image": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400",
        "tags": ["휴양", "해변", "사원", "힐링"],
    },
    {
        "id": 5,
        "name": "강릉",
        "category": "자연",
        "region": "국내",
        "price": 120000,
        "rating": 4.5,
        "description": "동해안의 아름다운 해변과 커피거리, 오죽헌 등 자연과 문화를 함께 즐길 수 있습니다.",
        "image": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400",
        "tags": ["해변", "카페", "자연", "동해"],
    },
    {
        "id": 6,
        "name": "파리",
        "category": "도시",
        "region": "해외",
        "price": 2500000,
        "rating": 4.8,
        "description": "예술과 낭만의 도시. 에펠탑, 루브르 박물관, 센강 크루즈 등 세계적 명소가 가득합니다.",
        "image": "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400",
        "tags": ["도시", "예술", "낭만", "유럽"],
    },
    {
        "id": 7,
        "name": "전주",
        "category": "역사",
        "region": "국내",
        "price": 80000,
        "rating": 4.4,
        "description": "한옥마을, 비빔밥, 막걸리로 유명한 전통문화의 도시입니다.",
        "image": "https://images.unsplash.com/photo-1563190730-1d9a3ac1dad0?w=400",
        "tags": ["한옥", "음식", "전통", "역사"],
    },
    {
        "id": 8,
        "name": "방콕",
        "category": "도시",
        "region": "해외",
        "price": 700000,
        "rating": 4.5,
        "description": "태국의 수도로 왕궁, 사원, 야시장 등 활기찬 문화와 저렴한 물가로 인기 있는 여행지입니다.",
        "image": "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=400",
        "tags": ["도시", "사원", "야시장", "태국"],
    },
    {
        "id": 9,
        "name": "설악산",
        "category": "자연",
        "region": "국내",
        "price": 60000,
        "rating": 4.6,
        "description": "대한민국 최고의 산악 여행지. 울산바위, 공룡능선, 대청봉 등 웅장한 풍경을 자랑합니다.",
        "image": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400",
        "tags": ["등산", "자연", "단풍", "국립공원"],
    },
    {
        "id": 10,
        "name": "세부",
        "category": "휴양",
        "region": "해외",
        "price": 800000,
        "rating": 4.7,
        "description": "필리핀의 해양 도시. 투명한 바다와 스쿠버다이빙, 아일랜드 호핑으로 유명합니다.",
        "image": "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
        "tags": ["해변", "다이빙", "휴양", "필리핀"],
    },
    {
        "id": 11,
        "name": "로마",
        "category": "역사",
        "region": "해외",
        "price": 2200000,
        "rating": 4.9,
        "description": "영원의 도시 로마. 콜로세움, 바티칸, 트레비 분수 등 역사적 유산이 가득합니다.",
        "image": "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400",
        "tags": ["역사", "유럽", "유네스코", "콜로세움"],
    },
    {
        "id": 12,
        "name": "부산",
        "category": "도시",
        "region": "국내",
        "price": 100000,
        "rating": 4.6,
        "description": "해운대, 광안리, 감천문화마을 등 바다와 도시가 어우러진 대한민국 제2의 도시입니다.",
        "image": "https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=400",
        "tags": ["도시", "해변", "해산물", "야경"],
    },
]
